### ISSUE TITLE
Error when sourcing harpoon.lua on Windows

### ISSUE THREAD

**Issue by H3AR7B3A7** [ThePrimeagen/init.lua#102]
Everything works fine for me on my Windows machine, except for sourcing the harpoon.lua:

```
Error detected while processing :source (no file):
E5108: Error executing lua [string ":source (no file)"]:1: module 'harpoon.mark' not found:
        no field package.preload['harpoon.mark']
        no file '.\harpoon\mark.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\harpoon\mark.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\harpoon\mark\init.lua'
        no file 'C:\Users\Admin\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\share\lua\5.1\harpoon\mark.lua'
        no file 'C:\Users\Admin\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\share\lua\5.1\harpoon\mark\init.lua'
        no file 'C:\Users\Admin\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\luarocks\rocks-5.1\harpoon\mark.lua'
        no file 'C:\Users\Admin\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\luarocks\rocks-5.1\harpoon\mark\init.lua'
        no file '.\harpoon\mark.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\harpoon\mark.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
        no file 'C:\Users\Admin\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\lua\5.1\harpoon\mark.so'
        no file '.\harpoon.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\harpoon.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
        no file 'C:\Users\Admin\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\lua\5.1\harpoon.so'
stack traceback:
        [C]: in function 'require'
        [string ":source (no file)"]:1: in main chunk
```

It doesn't seem to like this line:
`local mark = require("harpoon.mark")`

The error has a point that there are no mark.lua nor init.lua in any of these locations.

The only mark.lua file I can find on my system is located in LuaSnip, here:
C:\Users\Admin\AppData\Local\nvim-data\site\pack\packer\start\LuaSnip\lua\luasnip\util

Packer seems to install Harpoon just fine though.

NVIM v0.9.0

**Comment by H3AR7B3A7** [comment]
Nevermind, got it to work. I should have just checked the docks:
https://github.com/ThePrimeagen/harpoon

The harpoon.lua in this repo seems out of date.

**Comment by H3AR7B3A7** [comment]
Nevermind, got it to work. I should have just checked the docs:
https://github.com/ThePrimeagen/harpoon

The harpoon.lua in this repo seems out of date.

**Comment by ehxactly** [comment]
> Nevermind, got it to work. I should have just checked the docs: https://github.com/ThePrimeagen/harpoon
> 
> The harpoon.lua in this repo seems out of date.

Hey, can you advise on how you fixed it? I'm getting the same issue. New to this, so I don't know what I'm doing lol
