### ISSUE TITLE
What colorscheme is theprimeagen currently using?

### ISSUE THREAD

**Issue by RobertMiguel** [ThePrimeagen/init.lua#108]
![2024-01-07-153731_1366x768_scrot](https://github.com/ThePrimeagen/init.lua/assets/90520597/20fb6f9f-44e3-421a-81c9-2171a0cdafb4)

Is he still using rose-pine? If so, what rose-pine plugin settings did he make?

**Comment by missingcharacter** [comment]
@RobertMiguel I believe this is it:

```lua
function ColorMyPencils(color)
    color = color or "rose-pine"
    vim.cmd.colorscheme(color)
end

return {
    {
        "folke/tokyonight.nvim",
        config = function()
            require("tokyonight").setup({
                style = "storm",
                transparent = true,
                terminal_colors = true,
                styles = {
                    comments = { italic = false },
                    keywords = { italic = false },
                    sidebars = "dark",
                    floats = "dark",
                },
            })
        end,
    },
    {
        "rose-pine/neovim",
        name = "rose-pine",
        config = function()
            require("rose-pine").setup({ disable_background = true })

            vim.cmd("colorscheme rose-pine")
            ColorMyPencils()
        end,
    },
}
```

**Comment by Sama-004** [comment]
> @RobertMiguel I believe this is it:
> 
> file: `~/.config/nvim/lua/theprimeagen/lazy/colors.lua`
> 
> ```lua
> function ColorMyPencils(color)
>     color = color or "rose-pine"
>     vim.cmd.colorscheme(color)
> end
> 
> return {
>     {
>         "folke/tokyonight.nvim",
>         config = function()
>             require("tokyonight").setup({
>                 style = "storm",
>                 transparent = true,
>                 terminal_colors = true,
>                 styles = {
>                     comments = { italic = false },
>                     keywords = { italic = false },
>                     sidebars = "dark",
>                     floats = "dark",
>                 },
>             })
>         end,
>     },
>     {
>         "rose-pine/neovim",
>         name = "rose-pine",
>         config = function()
>             require("rose-pine").setup({ disable_background = true })
> 
>             vim.cmd("colorscheme rose-pine")
>             ColorMyPencils()
>         end,
>     },
> }
> ```

Don't think so the one he is using is much more darker

**Comment by Sama-004** [comment]
https://github.com/rebelot/kanagawa.nvim

It looks more like this

**Comment by AndreiMoraru123** [comment]
It's rose-pine. When you launch vim from tmux without the 256 color palette you get that.

**Comment by MSzarkowicz1** [comment]
isn't it due to transparent background ?

**Comment by RobertMiguel** [comment]
Thank you everyone, I managed to solve it with your instructions.

**Comment by HossamSamir** [comment]
@AndreiMoraru123 @RobertMiguel How can I disable the 256 color palette?
I've commented this line: `# set -g default-terminal "screen-256color"`
at my `~/.tmux.conf file`

And I'm opening neovim from a tmux session in iterm2, but still it does not look the same.

**Comment by RobertMiguel** [comment]
Which terminal do you use? Depending on this, you should also disable it in the terminal itself in addition to the .tmux.conf file settings

I use alacritty in case I only uncomment one line in my settings

alacritty.toml
```
[env]
TERM="xterm-256color"
```

**Comment by rajkothari4776** [comment]
Hi, I use alacritty with tmux, how to achieve this, in my alacritty.toml I have written [env] variable and what to do in tmux?? to achieve the colorscheme primeagen is using

**Comment by zedddie16** [comment]
```lua
  {
    'rose-pine/neovim',
    name = 'rose-pine',
    config = function()
      require('rose-pine').setup {
        styles = {
          bold = true,
          italic = false,
          transparency = true,
        },
      }
      vim.cmd 'colorscheme rose-pine'
    end,
  },
```
looks just like what he is using rn (with term transparency), but still 
his color scheme is just a bit tweaked rose-pine
