### ISSUE TITLE
`<leader>ps` not working without ripgrep

### ISSUE THREAD

**Issue by Sc4ramouche** [ThePrimeagen/init.lua#13]
Hey there! Thanks for "Neovim from scratch" video, it's so great!

One issue I stumbled upon is that [`<leader>ps`](https://github.com/ThePrimeagen/init.lua/blob/master/after/plugin/telescope.lua#L4-L6) didn't work on my system by default.

I searched through youtube comments to see if someone else had the same, and indeed someone did. The comment from the user `EmeraldWhovian`:

> Thanks for the content !
> An issue I had was setting the grep_string function. It didn't work, after checking :checkhealth, I found out it's because you need ripgrep installed on your system 

I went and installed [ripgrep](https://github.com/BurntSushi/ripgrep) as suggested and `<leader>ps` now works for me. Just thought I'll open an issue here in case more people run into the same thing, maybe it's worth a comment or something. Cheers!

**Comment by ThePrimeagen** [comment]
I am away from my computer for some time. Would you be willing to make a pull request to update the readme? You could put it as the second line?

**Comment by Sc4ramouche** [comment]
Sure thing, there you go: https://github.com/ThePrimeagen/init.lua/pull/15.

**Comment by Samathingamajig** [comment]
can you please put this in the pinned comment and/or description of the video? you already mention

> Requires neovim 0.9.x

so adding another requirement seems fair

**Comment by folfgirl** [comment]
I just install ripgrep still not working.
