### ISSUE TITLE
can any one help

### ISSUE THREAD

**Issue by th3gh0s8** [ThePrimeagen/init.lua#130]
![Screenshot_20241005_013635](https://github.com/user-attachments/assets/7f88c235-bb54-45a7-95d8-93d20b929464)

**Comment by mrayushmehrotra** [comment]
it simply say's the harpoon is not present in your directory,

goto local.lua file and add the harpoon by the ThePrimeagen/harpoon and remove the dir thing

**Comment by th3gh0s8** [comment]
> it simply say's the harpoon is not present in your directory,
> 
> goto local.lua file and add the harpoon by the ThePrimeagen/harpoon and remove the dir thing


### It's already there bro 
![Screenshot_20241006_210230](https://github.com/user-attachments/assets/b759e006-789f-45ad-985c-2d08e5a21cc3)

**Comment by th3gh0s8** [comment]
![Screenshot_20241006_211425](https://github.com/user-attachments/assets/30bd60f2-8dcf-4b62-bbb0-777635b0c81c)

### And there is this too

**Comment by SLRAPTOR** [comment]
I have the same issue too

**Comment by th3gh0s8** [comment]
> I have the same issue too

What to do man

**Comment by Zi0LEO** [comment]
> > it simply say's the harpoon is not present in your directory,
> > goto local.lua file and add the harpoon by the ThePrimeagen/harpoon and remove the dir thing
> 
> ### It's already there bro
> 
> ![Screenshot_20241006_210230](https://private-user-images.githubusercontent.com/89306822/373959413-b759e006-789f-45ad-985c-2d08e5a21cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDU3NDQsIm5iZiI6MTcyODY0NTQ0NCwicGF0aCI6Ii84OTMwNjgyMi8zNzM5NTk0MTMtYjc1OWUwMDYtNzg5Zi00NWFkLTk4NWMtMmQwOGU1YTIxY2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDExMTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTNhNDVlODkxMzI4NTBiYmQzM2VmNjRlNjE3YjYwMjBjYmNjOThmMWY1NDRkYjdmOTM2NDU1ODAwZjllOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4Oa6MUK7etlx8FD0v4KgGNn5usf-Nd3_WH-3_9jKGRY)

line 22 has to be "ThePrimeagen/harpoon", and delete line 21

**Comment by Zi0LEO** [comment]
> ![Screenshot_20241006_211425](https://private-user-images.githubusercontent.com/89306822/373960087-30bd60f2-8dcf-4b62-bbb0-777635b0c81c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDU3NDQsIm5iZiI6MTcyODY0NTQ0NCwicGF0aCI6Ii84OTMwNjgyMi8zNzM5NjAwODctMzBiZDYwZjItOGRjZi00YjYyLWJiYjAtNzc3NjM1YjBjODFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDExMTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YTJlNzVhODNjZTgwZWNiOWFhNGJhZTdlOTJjZTEyNmJkM2E0NWMxYzk0ZThiNmE2OGMyZDMxNjIwMzc5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7kag2JjyHYV1KP84QPQOzFscUGy97zbIxYKOTeLs368)
> ### And there is this too

Open another issue for this

**Comment by th3gh0s8** [comment]
> it simply say's the harpoon is not present in your directory,
> 
> goto local.lua file and add the harpoon by the ThePrimeagen/harpoon and remove the dir thing

Thank you, it worked <3
