### ISSUE TITLE
Should lua require('packer_<config...>')

### ISSUE THREAD

**Issue by KyleMcGregor** [ThePrimeagen/init.lua#26]
Guessing. 
using packer.lua for the packer config file doesn't result in running packer. I renamed packer.lua to packer_config.lua and import from the bottom level init.lua.

**Comment by andou-azarashi** [comment]
I use parker when I need it. I go to parker.lua, :so then :ParkerSync

**Comment by KyleMcGregor** [comment]
Makes sense.
