### ISSUE TITLE
Getting past errors to do PackerSync?

### ISSUE THREAD

**Issue by omar2205** [ThePrimeagen/init.lua#3]
How to bootstrap this config?

```
E5113: Error while calling lua chunk: /home/waifu3000/.config/nvim/after/plugin/colo
rs.lua:4: Vim:E185: Cannot find color scheme 'rose-pine'
```

Add to README to edit `:e lua/theprimeagen/packer.lua` and do `:so` then `:PackerSync` is available.

**Comment by ChikoShidori** [comment]
Actually you just had to watch the video

**Comment by omar2205** [comment]
> Actually you just had to watch the video

This is a problem that happened. And I provided a fix that future _users_ might need. If someone watched the video and wanted to try this config (idk why, if he watched the video then this repo isn't useful) would hit this problem.

**Comment by ThePrimeagen** [comment]
Yes, the video is the source of truth for this. I would expect some trivial error like this to be addressed by the video

Appreciate you trying to help.
