### ISSUE TITLE
after plugins not loading

### ISSUE THREAD

**Issue by SlikeDollar** [ThePrimeagen/init.lua#30]
so I cloned the repo into ~/.config/nvim and tried to open nvim
but got this error:

_Error detected while processing /home/slikedollar/.config/nvim/after/plugin/colors.lua:
E5113: Error while calling lua chunk: /home/slikedollar/.config/nvim/after/plugin/colors.lua:1: module 'rose-pine' not found:
        no field package.preload['rose-pine']
        no file './rose-pine.lua'
        no file '/usr/share/luajit-2.1.0-beta3/roseError detected while processing /home/slikedollar/.config/nvim/after/plugin/colors.lua:
E5113: Error while calling lua chunk: /home/slikedollar/.config/nvim/after/plugin/colors.lua:1: module 'rose-pine' not found:
        no field package.preload['rose-pine']
        no file './rose-pine.lua'
        no file '/usr/share/luajit-2.1.0-beta3/rose-pine.lua'
        no file '/usr/local/share/lua/5.1/rose-pine.lua'
        no file '/usr/local/share/lua/5.1/rose-pine/init.lua'
        no file '/usr/share/lua/5.1/rose-pine.lua'
        no file '/usr/share/lua/5.1/rose-pine/init.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rose-pine.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rose-pine/init.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rose-pine.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rose-pine/init.lua'
        no file './rose-pine.so'
        no file '/usr/local/lib/lua/5.1/rose-pine.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/rose-pine.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/rose-pine.so'
stack traceback:
       [C]: in function 'require'
        /home/slikedollar/.config/nvim/after/plugin/colors.lua:1: in main chunk-pine.lua'
        no file '/usr/local/share/lua/5.1/rose-pine.lua'
        no file '/usr/local/share/lua/5.1/rose-pine/init.lua'
        no file '/usr/share/lua/5.1/rose-pine.lua'
        no file '/usr/share/lua/5.1/rose-pine/init.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rose-pine.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rose-pine/init.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rose-pine.lua'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rose-pine/init.lua'
        no file './rose-pine.so'
        no file '/usr/local/lib/lua/5.1/rose-pine.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/rose-pine.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/mpaulson/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/rose-pine.so'
stack traceback:
       [C]: in function 'require'
        /home/slikedollar/.config/nvim/after/plugin/colors.lua:1: in main chunk_

i copied only one plugin output but its actually happens with all plugins in that directory. Any ideas of what can cause an issue?

**Comment by SlikeDollar** [comment]
heh, kinda forgot to source packer.lua after copying)

**Comment by Lohan-Yrvine** [comment]
Sorry, but I think I'm still doing something wrong.

```
require('iceberg').setup({
    disable_background = true,
})

function SetColorScheme(color)
    color = color or 'iceberg'
    vim.cmd.colorscheme(color)

    vim.api.nvim_set_hl(0, 'Normal', { bg = 'none', ctermbg = 'none' })
    vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none', ctermbg = 'none' })
end

--vim.keymap.set('n', '<leader>ss', SetColorScheme)

SetColorScheme()
```

This is my code in "colors.lua", I used `PackerSync` and I'm still getting this error.
