### ISSUE TITLE
Where are you importing your packer packages?

### ISSUE THREAD

**Issue by davidahmed** [ThePrimeagen/init.lua#39]
Where are you importing your `packer.lua` module. 

I can see this in your `packer.lua` 
```lua
-- This file can be loaded by calling `lua require('plugins')` from your init.vim
```

In your `./lua/theprimeagen/init.lua`, you're only importing 

```lua
require("theprimeagen.set")
require("theprimeagen.remap")
```

Will this work? If this will work, then why does it work? I.e. how can you have packer packages and not import it and yet you can `PackerSync`. I can't sleep thinkin about this.

**Comment by andou-azarashi** [comment]
You can put it the init.lua. And don't confuse, packer is package manager not the package it self, once you use packer to install the package, there is no need for the packer to load the package, is neovim load the package.

**Comment by davidahmed** [comment]
@andou-azarashi thanks for jumping in. That was my understanding as well. So it means that everytime you change packer packages, you `:so` it and then run `PackerInstall` right? v/s If you `require` it, then you don't have to `:so` as long as you restart the session or `:so` the `init.lua`.

**Comment by andou-azarashi** [comment]
Yes, but is not PackerInstall is PackerSync.
