### ISSUE TITLE
renamed sumneko_lua -> lua_ls and 'vim' global undefined

### ISSUE THREAD

**Issue by Artmade-studio** [ThePrimeagen/init.lua#49]
## Error
just finished setting up through the video and reading documentation however Mason.confi gave me this error :
_server "sumneko_lua" is not valid entry in ensure installed. makesure to only provid lspconfig server names_

## Finding
sumneko_lua just deprecated the name and change it to lua_ls 

## Issue
'vim' global undefined appearing everywhere there is vim in .lua files so is this not working? 
```js
lsp.configure('lua-ls', {
    settings = {
        Lua = {
            diagnostics = {
                globals = { 'vim' }
            }
        }
    }
})
```

**Comment by unfirthman** [comment]
I had this same issue and it drove me nuts yesterday!

I changed `sumneko_lua` to `lua-lsp` in `ensure_installed` as well as in `lsp.configure`

So far seems to work fine for me!

**Comment by unfirthman** [comment]
as an example:

```
lsp.ensure_installed({
  'tsserver',
  'eslint',
  'lua_ls',
  'rust_analyzer',
})

-- Fix Undefined global 'vim'
lsp.configure('lua_ls', {
    settings = {
        Lua = {
            diagnostics = {
                globals = { 'vim' }
            }
        }
    }
})
```

**Comment by Artmade-studio** [comment]
> as an example:
> 
> ```
> lsp.ensure_installed({
>   'tsserver',
>   'eslint',
>   'lua_ls',
>   'rust_analyzer',
> })
> 
> -- Fix Undefined global 'vim'
> lsp.configure('lua_ls', {
>     settings = {
>         Lua = {
>             diagnostics = {
>                 globals = { 'vim' }
>             }
>         }
>     }
> })
> ```

thanks that fixed 'vim' global undefined warning
