### ISSUE TITLE
Rose-pine colors are different in the video

### ISSUE THREAD

**Issue by mmskv** [ThePrimeagen/init.lua#58]
Hi, what could be causing ThePrimeagen's neovim colors to differ from rose-pine's defaults and how to reproduce that?

The difference appears in ThePrimeagen's video "Neovim RC from scratch" right after he installs rose-pine package. It also persists in all subsequent videos. Here is a comparison of his colors and actual rose-pine [defaults](https://github.com/rose-pine/neovim#user-content-gallery).

![comparison](https://user-images.githubusercontent.com/47359245/223853994-473bf827-3338-45cc-a776-de2f8c039d4f.png)

Following steps in the video does not produce such colors and I couldn't find any configuration in ThePrimeagen's dotfiles that could cause this.

**Comment by yok0** [comment]
Did you try removing this two lines from colors.lua

`	vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
`

**Comment by mmskv** [comment]
@yok0, at the point of screenshot he had no colors.lua file

**Comment by daniel-abramov** [comment]
I may assume that it was due to the background being a bit transparent for the terminal emulator that is used by ThePrimeagen (as I was not able to get the same colors, although I would enjoy using his color scheme I think).

I do find the color scheme as rendered in his terminal a bit more pleasant than the original colors from the `rose-pine` though!

**Comment by mmskv** [comment]
@daniel-abramov, good catch! I've played with screenshot's opacity and saturation and was able to get exactly the same background color by setting screenshot's saturation to 0. And all foreground colors except `return`'s can be made to look sameish by modifying saturation too.
I am not aware of any way Primeagen's terminal could somehow modify TrueColor (24-bit) produced by Neovim to have such effect.

**Comment by BenCassidy33** [comment]
I know its been a while since this comment has been posted but I think i have the solution. I ran into the same colors as he had in his video while having an active tmux session. I have no idea why tmux would change the colors inside of neovim but that is what happened to me.

**Comment by mmskv** [comment]
@BenCassidy33 thank you! I can reproduce that and tmux with default config does change the colors.
