### ISSUE TITLE
How is packer.lua sourced?

### ISSUE THREAD

**Issue by MarcSchaetz** [ThePrimeagen/init.lua#7]
I just watched the Youtube video and checked the source code. 

I don't really understand how the packer.lua is sourced, because when I open neovim and try to call `PackerInstall` the function is not accessible, without me explicitly add `require("theprimeagen.packer")`

Could this be a missing require statement or did I overlook something?

**Comment by ThePrimeagen** [comment]
So I manually source packer when I need to. I found that I had a bit of lag playing around with packer. So I only source it and use it when I need to update my plugins. Which is rather infrequent. A strategy might be to source the packer file with a remap. That's way you don't have to have it sourced all the time unless if you need it in the moment.

**Comment by MarcSchaetz** [comment]
> So I manually source packer when I need to. I found that I had a bit of lag playing around with packer. So I only source it and use it when I need to update my plugins. Which is rather infrequent. A strategy might be to source the packer file with a remap. That's way you don't have to have it sourced all the time unless if you need it in the moment.

Understood. Thanks for clarifying!
