### ISSUE TITLE
Erorr while sourcing colors.lua

### ISSUE THREAD

**Issue by umairmaratab** [ThePrimeagen/init.lua#81]
When I try to source colors.lua file it says:

![Screenshot from 2023-06-15 13-52-16](https://github.com/ThePrimeagen/init.lua/assets/43462082/d4b5e3e8-9f86-4056-a0f7-c19cebf2f87b)

I copied the exact content from colors.lua file in after/plugin directory.

Thanks in advance for your help.

**Comment by mehmetrecep** [comment]
I think after saving the colors.lua you have to call the function ColorMyPencils() by typing :lua ColorMyPencils()

**Comment by umairmaratab** [comment]
Thanks for your answer.
Same Error.

**Comment by mehmetrecep** [comment]
I don't if you use it after accessing to the directory of nvim after writing nvim . in the terminal.
you're welcome bro

**Comment by mehmetrecep** [comment]
That's the code that I wrote :

function ColorMyPencils(color)
	color = color or "rose-pine"
	vim.cmd.colorscheme(color)

	vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
end

ColorMyPencils()

you can use it and try again.

**Comment by umairmaratab** [comment]
I think error is somewhere else, as when I execute `nvim .` it says:

Error detected while processing /home/umair/.local/share/nvim/site/pack/packer/start/rose-pine/colors
/rose-pine.lua:
W18: Invalid character in group name

**Comment by umairmaratab** [comment]
Full description of error:
Error detected while processing /home/user-name/.local/share/nvim/site/pack/packer/start/rose-pine/colors
/rose-pine.lua:
W18: Invalid character in group name
.
.
.
W18: Invalid character in group name

Error detected while processing /home/user-name/.config/nvim/after/plugin/colors.lua:
E5113: Error while calling lua chunk: /home/user-name/.config/nvim/after/plugin/colors.lua:7: attempt to
index field 'cmd' (a function value)
stack traceback:
        /home/user-name/.config/nvim/after/plugin/colors.lua:7: in function 'ColorMyPencils'
        /home/user-name/.config/nvim/after/plugin/colors.lua:14: in main chunk
Press ENTER or type command to continue

**Comment by mehmetrecep** [comment]
if you're using mac or linux the file must be at .config/ or configuration folder if you're using windows. I think the path is the reason

**Comment by mehmetrecep** [comment]
you can see this issue:
https://github.com/neovim/neovim/issues/14202

**Comment by umairmaratab** [comment]
Thank u it was actually due to older version of nvim.
I installed via source and now everything is fine.
