### ISSUE TITLE
pressing Tab doesnt autocomplete

### ISSUE THREAD

**Issue by agustinaguero97** [ThePrimeagen/init.lua#83]
i dont know how to explain it except using an example:

While editing a file (a .py for example), tipyng `s`, lsp suggest:
```python
sorted(iterable, key, reverse)
```
if i press `Tab`, it just jumps 4 spaces, pressing `C-y` autocompletes, but just `sorted`

My .config/nvim is pretty much the one that appears on the video

**Comment by mrs4ndman** [comment]
ThePrimeagen has his config set-up for mappings without tabs:
```Lua
local cmp = require('cmp')
local cmp_select = {behavior = cmp.SelectBehavior.Select}
local cmp_mappings = lsp.defaults.cmp_mappings({
  ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
  ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
  ['<C-y>'] = cmp.mapping.confirm({ select = true }),
  ["<C-Space>"] = cmp.mapping.complete(),
})

cmp_mappings['<Tab>'] = nil
cmp_mappings['<S-Tab>'] = nil

lsp.setup_nvim_cmp({
  mapping = cmp_mappings
})
```
His keybinds for completion are <kbd>C-n</kbd> for next completion item, <kbd>C-p</kbd> for the previous one, <kbd>C-y</kbd> for completion confirmation (as you commented earlier), and <kbd>C-Space</kbd> for completing but not accepting the completion (even I myself don't understand how this works).

If you want to change it in your local one to have Tab-key completion, search for how to do it on [lsp-zero's GitHub](https://github.com/VonHeikemen/lsp-zero.nvim)
Hope this helps :)

**Comment by agustinaguero97** [comment]
thanks for the help, i fixed it with this `cmp.setup`
```lua
local cmp_action = require('lsp-zero').cmp_action()
cmp.setup({
      mapping = {
            ['<CR>'] = cmp.mapping.confirm({select = true}),
            ['<Tab>'] = cmp_action.tab_complete(),
            ['<S-Tab>'] = cmp_action.select_prev_or_fallback(),
     }
})
```
